import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "../components/navigation/Navigation";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" className=" text-white h-full ">
      <body className="flex sm:flex-row sm:h-full ${inter.className}">
        <Navigation user={session?.user} expires={session?.expires as string} />
        <div className="w-96 mx-auto mt-2 sm:w-4/5 overflow-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
